name: 'Run E2E Tests'
description: 'Starts backend server, waits for readiness, and runs Playwright e2e tests'

inputs:
  gemini-api-key:
    description: 'Gemini API key'
    required: true
  database-url:
    description: 'Database connection URL'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run e2e tests with server
      env:
        GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
        DATABASE_URL: ${{ inputs.database-url }}
        JWT_SECRET: test-jwt-secret-for-e2e
        NODE_ENV: test
      run: |
        npm run migrate
        npm run server &
        sleep 5
        npx wait-on http://127.0.0.1:3001/api/health --timeout 120000
        npm run test:e2e
      shell: bash
