name: 'Run E2E Tests'
description: 'Starts backend server, waits for readiness, and runs Playwright e2e tests'

inputs:
  gemini-api-key:
    description: 'Gemini API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run e2e tests with server
      run: |
        npm run server &
        for i in {1..30}; do
          if curl -f http://127.0.0.1:3001/api/health > /dev/null 2>&1; then
            echo "Backend is up!"
            break
          fi
          sleep 1
        done
        npm run test:e2e
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
