name: 'Run E2E Tests'
description: 'Starts backend server, waits for readiness, and runs Playwright e2e tests'

inputs:
  gemini-api-key:
    description: 'Gemini API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run e2e tests with server
      run: |
        npm run server &
        npx wait-on http://127.0.0.1:3001/api/health --timeout 30000
        npm run test:e2e
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
