name: 'Bundle Size'
description: 'Check bundle size changes and comment on PRs'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Build
      run: npm run build
      shell: bash

    - name: Compressed Size Action
      uses: preactjs/compressed-size-action@v2
      with:
        repo-token: ${{ github.token }}
